name: spark
description: "Student Data Management App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  date_field: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  path: ^1.8.3
  intl: ^0.18.1
  logger: 2.0.2+1
  sqflite_common_ffi: ^2.1.1+1
  flutter_riverpod: ^2.4.9  
  http: ^1.2.0
  flutter_speed_dial: ^7.0.0 
  easy_dynamic_theme: ^2.3.1
  fl_chart: ^0.66.2
  animated_splash_screen: ^1.3.0
  sqlite3_flutter_libs: ^0.5.20
  drift_sqflite: ^2.0.1
  analyzer: ^6.2.0
  provider: ^6.1.2
  mongo_dart: ^0.10.0
  realm: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/